// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ChannelCommunityVali struct {
	CommunityValiID string `json:"CommunityValiID"`
	UserID          string `json:"userID"`
	CommunityID     string `json:"CommunityID"`
	Like            bool   `json:"like"`
	Dislike         bool   `json:"dislike"`
}

type Playlist struct {
	PlaylistID        string `json:"playlistID"`
	UserID            string `json:"userID"`
	VideoID           string `json:"videoID"`
	PlaylistHeader    string `json:"playlistHeader"`
	PlaylistType      bool   `json:"playlistType"`
	Description       string `json:"description"`
	PriorityWeight    int    `json:"priorityWeight"`
	DatePublish       string `json:"datePublish"`
	DateAddToPlaylist string `json:"dateAddToPlaylist"`
	Views             int    `json:"views"`
	TotalVideo        int    `json:"totalVideo"`
}

type User struct {
	ID              string  `json:"id"`
	Email           string  `json:"email"`
	Username        string  `json:"username"`
	Premium         bool    `json:"premium"`
	Location        string  `json:"location"`
	Subscribers     int     `json:"subscribers"`
	Restriction     bool    `json:"restriction"`
	PremiumDayCount int     `json:"premiumDayCount"`
	Thumbnail       *string `json:"thumbnail"`
	Date            string  `json:"date"`
}

type VideoLikeVali struct {
	UserID  string `json:"userID"`
	VideoID string `json:"videoID"`
	Like    bool   `json:"like"`
	Dislike bool   `json:"dislike"`
}

type VideoReplyLikeVali struct {
	UserID  string `json:"userID"`
	VideoID string `json:"videoID"`
	ReplyID string `json:"replyID"`
	Like    bool   `json:"like"`
	Dislike bool   `json:"dislike"`
}

type VideoReplyRepliesLikeVali struct {
	VideoReplyRepliesLikeValiID string `json:"videoReplyRepliesLikeValiID"`
	ReplyRepliesID              string `json:"replyRepliesID"`
	UserID                      string `json:"userID"`
	ReplyID                     string `json:"replyID"`
	VideoID                     string `json:"videoID"`
	Like                        bool   `json:"like"`
	Dislike                     bool   `json:"dislike"`
}

type ChannelLink struct {
	ChannelLinkID string `json:"channelLinkID"`
	UserID        string `json:"userID"`
	Link          string `json:"link"`
}

type NewChannel struct {
	UserID       string `json:"userID"`
	Location     string `json:"location"`
	ChannelImage string `json:"channelImage"`
}

type NewChannelCommunity struct {
	ChannelID      string `json:"channelID"`
	UserID         string `json:"userID"`
	Day            int    `json:"day"`
	Month          int    `json:"month"`
	Year           int    `json:"year"`
	ComDescription string `json:"comDescription"`
}

type NewChannelLink struct {
	UserID string `json:"userID"`
	Link   string `json:"link"`
}

type NewPlaylist struct {
	UserID         string `json:"userID"`
	PlaylistHeader string `json:"playlistHeader"`
	PlaylistType   bool   `json:"playlistType"`
	Description    string `json:"description"`
}

type NewPlaylistSubscribe struct {
	PlaylistID string `json:"playlistID"`
	UserID     string `json:"userID"`
}

type NewReplyReplies struct {
	ReplyID     string `json:"replyID"`
	UserID      string `json:"userID"`
	Day         *int   `json:"day"`
	Month       *int   `json:"month"`
	Year        *int   `json:"year"`
	Description string `json:"description"`
}

type NewUser struct {
	Email     string  `json:"email"`
	Username  string  `json:"username"`
	Location  string  `json:"location"`
	Thumbnail *string `json:"thumbnail"`
}

type NewUserSubscribe struct {
	UserID        string `json:"userID"`
	ChannelID     string `json:"channelID"`
	ChannelUserID string `json:"channelUserID"`
}

type NewVideo struct {
	UserID       string  `json:"userID"`
	Title        *string `json:"title"`
	Thumbnail    *string `json:"thumbnail"`
	Day          *int    `json:"day"`
	Month        *int    `json:"Month"`
	Year         *int    `json:"Year"`
	Descriptions *string `json:"descriptions"`
	SourceLink   *string `json:"sourceLink"`
	Category     *string `json:"category"`
	VideoLength  *int    `json:"VideoLength"`
	Location     *string `json:"location"`
	Premium      *bool   `json:"premium"`
	Restriction  *bool   `json:"restriction"`
	TypePub      bool    `json:"typePub"`
}

type NewVideoLikeVali struct {
	UserID  string `json:"userID"`
	VideoID string `json:"videoID"`
}

type NewVideoReply struct {
	UserID      string `json:"userID"`
	VideoID     string `json:"videoID"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
	Description string `json:"description"`
}

type NewVideoReplyLikeVali struct {
	UserID  string `json:"userID"`
	VideoID string `json:"videoID"`
	ReplyID string `json:"replyID"`
}

type NewVideoReplyRepliesLikeVali struct {
	UserID         string `json:"userID"`
	ReplyRepliesID string `json:"replyRepliesID"`
	ReplyID        string `json:"replyID"`
	VideoID        string `json:"videoID"`
}

type NewVideoToPlaylist struct {
	PlaylistID string `json:"playlistID"`
	UserID     string `json:"userID"`
	VideoID    string `json:"videoID"`
}

type NewchannelCommunityVali struct {
	UserID      string `json:"userID"`
	CommunityID string `json:"CommunityID"`
}

type PlaylistSubscribe struct {
	PlaylistID string `json:"playlistID"`
	UserID     string `json:"userID"`
	Subscribe  bool   `json:"subscribe"`
}

type UserSubscribe struct {
	UserID        string `json:"userID"`
	ChannelID     string `json:"channelID"`
	Subscribe     bool   `json:"subscribe"`
	ChannelUserID string `json:"channelUserID"`
}
