// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Channel struct {
	ChannelID          string  `json:"channelID"`
	UserID             string  `json:"userID"`
	ViewCount          *int    `json:"viewCount"`
	Location           *string `json:"location"`
	ChannelDescription *string `json:"channelDescription"`
	ChannelImage       *string `json:"ChannelImage"`
}

type ChannelCommunity struct {
	CommunityID    string `json:"communityID"`
	ChannelID      string `json:"channelID"`
	UserID         string `json:"userID"`
	ComDescription string `json:"comDescription"`
	Like           int    `json:"like"`
	Dislike        int    `json:"dislike"`
}

type Playlist struct {
	PlaylistID     string `json:"playlistID"`
	UserID         string `json:"userID"`
	VideoID        string `json:"videoID"`
	PriorityWeight *int   `json:"priorityWeight"`
}

type ReplyReplies struct {
	ReplyRepliesID string `json:"replyRepliesID"`
	ReplyID        string `json:"replyID"`
	UserID         string `json:"userID"`
	Like           int    `json:"like"`
	Dislike        int    `json:"dislike"`
	Description    string `json:"description"`
}

type User struct {
	ID              string  `json:"id"`
	Email           *string `json:"email"`
	Username        *string `json:"username"`
	Premium         *bool   `json:"premium"`
	Location        *string `json:"location"`
	Subscribers     *int    `json:"subscribers"`
	PremiumDayCount *int    `json:"premiumDayCount"`
}

type Video struct {
	VideoID      string  `json:"videoID"`
	UserID       string  `json:"userID"`
	Title        *string `json:"title"`
	Views        *int    `json:"views"`
	Day          *int    `json:"day"`
	Month        *int    `json:"month"`
	Year         *int    `json:"year"`
	Like         *int    `json:"like"`
	Dislike      *int    `json:"dislike"`
	Descriptions *string `json:"descriptions"`
	SourceLink   *string `json:"sourceLink"`
	Category     *string `json:"category"`
	VideoLength  *int    `json:"videoLength"`
	Restriction  *bool   `json:"restriction"`
	Premium      *bool   `json:"premium"`
}

type VideoLikeVali struct {
	UserID  string `json:"userID"`
	VideoID string `json:"videoID"`
	Like    bool   `json:"like"`
	Dislike bool   `json:"dislike"`
}

type VideoReply struct {
	ReplyID     string `json:"replyID"`
	UserID      string `json:"userID"`
	VideoID     string `json:"videoID"`
	Likes       int    `json:"likes"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
	Dislikes    int    `json:"dislikes"`
	Description string `json:"description"`
}

type VideoReplyLikeVali struct {
	UserID  string `json:"userID"`
	VideoID string `json:"videoID"`
	ReplyID string `json:"replyID"`
	Like    *bool  `json:"like"`
	Dislike *bool  `json:"dislike"`
}

type VideoReplyRepliesLikeVali struct {
	VideoReplyRepliesLikeValiID string `json:"videoReplyRepliesLikeValiID"`
	UserID                      string `json:"userID"`
	ReplyID                     string `json:"replyID"`
	VideoID                     string `json:"videoID"`
	Like                        *bool  `json:"like"`
	Dislike                     *bool  `json:"dislike"`
}

type NewChannel struct {
	ChannelID          string  `json:"channelID"`
	UserID             string  `json:"userID"`
	ViewCount          *int    `json:"viewCount"`
	Location           *string `json:"location"`
	ChannelDescription *string `json:"channelDescription"`
	ChannelImage       *string `json:"channelImage"`
}

type NewChannelCommunity struct {
	CommunityID    string `json:"communityID"`
	ChannelID      string `json:"channelID"`
	UserID         string `json:"userID"`
	ComDescription string `json:"comDescription"`
	Like           int    `json:"like"`
	Dislike        int    `json:"dislike"`
}

type NewPlaylist struct {
	PlaylistID     string `json:"playlistID"`
	UserID         string `json:"userID"`
	VideoID        string `json:"videoID"`
	PriorityWeight *int   `json:"priorityWeight"`
}

type NewReplyReplies struct {
	ReplyRepliesID string `json:"replyRepliesID"`
	ReplyID        string `json:"replyID"`
	UserID         string `json:"userID"`
	Like           int    `json:"like"`
	Dislike        int    `json:"dislike"`
	Description    string `json:"description"`
}

type NewUser struct {
	ID       string  `json:"id"`
	Email    *string `json:"email"`
	Username *string `json:"username"`
	Location *string `json:"location"`
}

type NewUserSubscribe struct {
	UserID    string `json:"userID"`
	ChannelID string `json:"channelID"`
}

type NewVideo struct {
	VideoID      string  `json:"videoID"`
	UserID       string  `json:"userID"`
	Title        *string `json:"title"`
	Day          *int    `json:"day"`
	Month        *int    `json:"Month"`
	Year         *int    `json:"Year"`
	Descriptions *string `json:"descriptions"`
	SourceLink   *string `json:"sourceLink"`
	Category     *string `json:"category"`
	VideoLength  *int    `json:"VideoLength"`
	Restriction  *bool   `json:"restriction"`
	Premium      *bool   `json:"premium"`
}

type NewVideoLikeVali struct {
	UserID  string `json:"userID"`
	VideoID string `json:"videoID"`
	Like    bool   `json:"like"`
	Dislike bool   `json:"dislike"`
}

type NewVideoReply struct {
	ReplyID     string `json:"replyID"`
	UserID      string `json:"userID"`
	VideoID     string `json:"videoID"`
	Day         int    `json:"day"`
	Month       int    `json:"month"`
	Year        int    `json:"year"`
	Description string `json:"description"`
}

type NewVideoReplyLikeVali struct {
	UserID  string `json:"userID"`
	VideoID string `json:"videoID"`
	ReplyID string `json:"replyID"`
	Like    *bool  `json:"like"`
	Dislike *bool  `json:"dislike"`
}

type NewVideoReplyRepliesLikeVali struct {
	VideoReplyRepliesLikeValiID string `json:"videoReplyRepliesLikeValiID"`
	UserID                      string `json:"userID"`
	ReplyID                     string `json:"replyID"`
	VideoID                     string `json:"videoID"`
	Like                        *bool  `json:"like"`
	Dislike                     *bool  `json:"dislike"`
}

type UserSubscribe struct {
	UserID    string `json:"userID"`
	ChannelID string `json:"channelID"`
}
